from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.skala1 = QtWidgets.QCheckBox(self.centralwidget)
        self.skala1.setGeometry(QtCore.QRect(110, 290, 161, 20))
        self.skala1.setObjectName("skala1")
        self.skala1_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.skala1_2.setGeometry(QtCore.QRect(110, 320, 161, 20))
        self.skala1_2.setObjectName("skala1_2")
        self.skala1_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.skala1_3.setGeometry(QtCore.QRect(110, 350, 161, 20))
        self.skala1_3.setObjectName("skala1_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(370, 290, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(370, 330, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(370, 370, 121, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 290, 55, 16))
        self.label.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 330, 55, 16))
        self.label_2.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 370, 55, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.activated['int'].connect(self.label.setNum)
        self.comboBox_2.activated['int'].connect(self.label_2.setNum)
        self.comboBox_3.activated['int'].connect(self.label_3.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.skala1.setText(_translate("MainWindow", "skala logarymiczna1"))
        self.skala1_2.setText(_translate("MainWindow", "skala logarymiczna1"))
        self.skala1_3.setText(_translate("MainWindow", "skala logarymiczna1"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Wybierz kanał"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Kanał 20"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Wybierz kanał"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "Kanał 20"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Wybierz kanał"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "Kanał 20"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
