# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kliczek = QtWidgets.QPushButton(self.centralwidget)
        self.kliczek.setGeometry(QtCore.QRect(220, 150, 371, 251))
        self.kliczek.setObjectName("kliczek")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.kliczek.clicked.connect(self.show_popup)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kliczek.setText(_translate("MainWindow", "Kliknij se to coś wyskoczy"))

    def show_popup(self):
        msg =QMessageBox()
        msg.setWindowTitle("Sprawdzamy komunikaty")
        msg.setText("Taki o se komunikat")

        #msg.setIcon(QMessageBox.Critical)
        #msg.setIcon(QMessageBox.Warning)
        #msg.setIcon(QMessageBox.Information)
        msg.setIcon(QMessageBox.Question)

        msg.setStandardButtons(QMessageBox.Ok|QMessageBox.Open|QMessageBox.Save)
        msg.setDefaultButton(QMessageBox.Ok)
        msg.setInformativeText("coś ci powiem")
        msg.setDetailedText("Szczegóły")
        msg.buttonClicked.connect(self.popup_button)
        x = msg.exec_()  


    def popup_button(self,i):
        print(i.text())


      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
