# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(90, 90, 141, 61))
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(420, 90, 141, 61))
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 250, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.klik = QtWidgets.QPushButton(self.centralwidget)
        self.klik.setGeometry(QtCore.QRect(280, 400, 161, 61))
        self.klik.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.klik.clicked.connect(self.pressed)

        self.comboBox2.addItem("jaja")
        index = self.comboBox2.findText("jaja",QtCore.Qt.MatchFixedString)
        self.comboBox2.setCurrentIndex(index)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "hehe"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Wynik"))
        self.klik.setText(_translate("MainWindow", "licz to"))

    def pressed(self):
        a=self.comboBox1.currentText()
        b=self.comboBox2.currentText()

        self.label.setText("Wynik to " +a+" "+b)
        print(a,b)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
