
from PyQt5 import QtCore, QtGui, QtWidgets

#<---------------------------
import matplotlib
matplotlib.use('Qt5Agg')        # używamy QT5
import wykres
import grzalka
import miernik20 
import csv
import time
import numpy as np
#----------------------->

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

#<----glówne okno-----
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1180, 750))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setLineWidth(5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_pomiar_oporu = QtWidgets.QWidget()
        self.page_pomiar_oporu.setObjectName("page_pomiar_oporu")
#-------------->

#<----obszary wykresów------
        self.widget_temp = QtWidgets.QWidget(self.page_pomiar_oporu)
        self.widget_temp.setGeometry(QtCore.QRect(40, 90, 450, 260))
        self.widget_temp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_temp.setObjectName("widget_temp")
        self.widget_probka1 = QtWidgets.QWidget(self.page_pomiar_oporu)
        self.widget_probka1.setGeometry(QtCore.QRect(40, 400, 530, 300))
        self.widget_probka1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_probka1.setObjectName("widget_probka1")
        self.widget_probka2 = QtWidgets.QWidget(self.page_pomiar_oporu)
        self.widget_probka2.setGeometry(QtCore.QRect(610, 400, 530, 300))
        self.widget_probka2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_probka2.setObjectName("widget_probka2")
#---------------->

#<-----czekboxy skalalog----------
        self.skala_temp = QtWidgets.QCheckBox(self.page_pomiar_oporu)
        self.skala_temp.setGeometry(QtCore.QRect(50, 355, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.skala_temp.setFont(font)
        self.skala_temp.setObjectName("skala_temp")

        self.skala_probka1 = QtWidgets.QCheckBox(self.page_pomiar_oporu)
        self.skala_probka1.setGeometry(QtCore.QRect(50, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.skala_probka1.setFont(font)
        self.skala_probka1.setObjectName("skala_probka1")

        self.skala_probka2 = QtWidgets.QCheckBox(self.page_pomiar_oporu)
        self.skala_probka2.setGeometry(QtCore.QRect(620, 705, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.skala_probka2.setFont(font)
        self.skala_probka2.setObjectName("skala_probka2")
#---------------------->

#<---kanały probka 1-------------
        self.comboBox_kanaly1 = QtWidgets.QComboBox(self.page_pomiar_oporu)
        self.comboBox_kanaly1.setGeometry(QtCore.QRect(270, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_kanaly1.setFont(font)
        self.comboBox_kanaly1.setObjectName("comboBox_kanaly1")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
        self.comboBox_kanaly1.addItem("")
#----------->

#<---------kanały próbka 2---------
        self.comboBox_kanaly2 = QtWidgets.QComboBox(self.page_pomiar_oporu)
        self.comboBox_kanaly2.setGeometry(QtCore.QRect(840, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_kanaly2.setFont(font)
        self.comboBox_kanaly2.setObjectName("comboBox_kanaly2")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
        self.comboBox_kanaly2.addItem("")
#---------------->

#-------wybór kanałow i osi----
        self.label_wybor1 = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_wybor1.setGeometry(QtCore.QRect(170, 705, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wybor1.setFont(font)
        self.label_wybor1.setObjectName("label_wybor1")

        self.label_danex1 = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_danex1.setGeometry(QtCore.QRect(390, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_danex1.setFont(font)
        self.label_danex1.setObjectName("label_danex1")

        self.comboBox_osx1 = QtWidgets.QComboBox(self.page_pomiar_oporu)
        self.comboBox_osx1.setGeometry(QtCore.QRect(470, 705, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_osx1.setFont(font)
        self.comboBox_osx1.setObjectName("comboBox_osx1")
        self.comboBox_osx1.addItem("")
        self.comboBox_osx1.addItem("")

        self.label_wybor2 = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_wybor2.setGeometry(QtCore.QRect(740, 705, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wybor2.setFont(font)
        self.label_wybor2.setObjectName("label_wybor2")

        self.label_danex2 = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_danex2.setGeometry(QtCore.QRect(960, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_danex2.setFont(font)
        self.label_danex2.setObjectName("label_danex2")

        self.comboBox_osx2 = QtWidgets.QComboBox(self.page_pomiar_oporu)
        self.comboBox_osx2.setGeometry(QtCore.QRect(1040, 705, 78, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_osx2.setFont(font)
        self.comboBox_osx2.setObjectName("comboBox_osx2")
        self.comboBox_osx2.addItem("")
        self.comboBox_osx2.addItem("")

        self.label_wybor1_2 = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_wybor1_2.setGeometry(QtCore.QRect(280, 355, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wybor1_2.setFont(font)
        self.label_wybor1_2.setObjectName("label_wybor1_2")
#------------->

#<------wybór kanały temeperatura----
        self.comboBox_kanaly0 = QtWidgets.QComboBox(self.page_pomiar_oporu)
        self.comboBox_kanaly0.setGeometry(QtCore.QRect(380, 355, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_kanaly0.setFont(font)
        self.comboBox_kanaly0.setObjectName("comboBox_kanaly0")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
        self.comboBox_kanaly0.addItem("")
#----------->

#<-----start----
        self.pushButton_start = QtWidgets.QPushButton(self.page_pomiar_oporu)
        self.pushButton_start.setGeometry(QtCore.QRect(970, 240, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
#-------------->

#<----czestotliwość-----
        self.doubleSpinBox_czestotliowsc = QtWidgets.QDoubleSpinBox(self.page_pomiar_oporu)
        self.doubleSpinBox_czestotliowsc.setGeometry(QtCore.QRect(800, 208, 65, 22))
        self.doubleSpinBox_czestotliowsc.setMinimum(1.0)
        self.doubleSpinBox_czestotliowsc.setMaximum(300.0)
        self.doubleSpinBox_czestotliowsc.setSingleStep(1.0)
        self.doubleSpinBox_czestotliowsc.setProperty("value", 3.0)
        self.doubleSpinBox_czestotliowsc.setObjectName("doubleSpinBox_czestotliowsc")
        
        self.label_czestotliwosc = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_czestotliwosc.setGeometry(QtCore.QRect(540, 210, 171, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_czestotliwosc.setFont(font)
        self.label_czestotliwosc.setAcceptDrops(False)
        self.label_czestotliwosc.setAutoFillBackground(False)
        self.label_czestotliwosc.setTextFormat(QtCore.Qt.AutoText)
        self.label_czestotliwosc.setWordWrap(True)
        self.label_czestotliwosc.setObjectName("label_czestotliwosc")
#------------>

#<--------automatycznie śledzenie i tempo
        self.label_srednie_tempo = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_srednie_tempo.setGeometry(QtCore.QRect(850, 258, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_srednie_tempo.setFont(font)
        self.label_srednie_tempo.setObjectName("label_srednie_tempo")

        self.label_tempo = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_tempo.setGeometry(QtCore.QRect(540, 250, 201, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_tempo.setFont(font)
        self.label_tempo.setAcceptDrops(False)
        self.label_tempo.setAutoFillBackground(False)
        self.label_tempo.setTextFormat(QtCore.Qt.AutoText)
        self.label_tempo.setWordWrap(True)
        self.label_tempo.setObjectName("label_tempo")


        self.label_automtyczne = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_automtyczne.setGeometry(QtCore.QRect(540, 306, 209, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_automtyczne.setFont(font)
        self.label_automtyczne.setAcceptDrops(False)
        self.label_automtyczne.setAutoFillBackground(False)
        self.label_automtyczne.setTextFormat(QtCore.Qt.AutoText)
        self.label_automtyczne.setWordWrap(True)
        self.label_automtyczne.setObjectName("label_automtyczne")

        self.doubleSpinBox_sledzenie = QtWidgets.QDoubleSpinBox(self.page_pomiar_oporu)
        self.doubleSpinBox_sledzenie.setGeometry(QtCore.QRect(800, 311, 70, 22))
        self.doubleSpinBox_sledzenie.setMinimum(-100.0)
        self.doubleSpinBox_sledzenie.setMaximum(100.0)
        self.doubleSpinBox_sledzenie.setProperty("value", 1.0)
        self.doubleSpinBox_sledzenie.setObjectName("doubleSpinBox_sledzenie")

        self.checkBox_sledzenie = QtWidgets.QCheckBox(self.page_pomiar_oporu)
        self.checkBox_sledzenie.setGeometry(QtCore.QRect(750, 310, 16, 16))
        self.checkBox_sledzenie.setText("")
        self.checkBox_sledzenie.setObjectName("checkBox_sledzenie")
#-------------->

#<---temeperatura-----
        self.label_aktualna_moc_wartosc = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_aktualna_moc_wartosc.setGeometry(QtCore.QRect(850, 130, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_aktualna_moc_wartosc.setFont(font)
        self.label_aktualna_moc_wartosc.setObjectName("label_aktualna_moc_wartosc")
        self.label_aktualna_temp = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_aktualna_temp.setGeometry(QtCore.QRect(540, 170, 140, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_aktualna_temp.setFont(font)
        self.label_aktualna_temp.setObjectName("label_aktualna_temp")

        self.label_aktualna_temp_wartosc = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_aktualna_temp_wartosc.setGeometry(QtCore.QRect(850, 170, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_aktualna_temp_wartosc.setFont(font)
        self.label_aktualna_temp_wartosc.setObjectName("label_aktualna_temp_wartosc")
#-------->
    
#<---------moc-----
        self.label_aktualna_moc = QtWidgets.QLabel(self.page_pomiar_oporu)
        self.label_aktualna_moc.setGeometry(QtCore.QRect(540, 130, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_aktualna_moc.setFont(font)
        self.label_aktualna_moc.setObjectName("label_aktualna_moc")

        self.horizontalSlider = QtWidgets.QSlider(self.page_pomiar_oporu)
        self.horizontalSlider.setGeometry(QtCore.QRect(910, 128, 191, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
#---------->
        self.stackedWidget.addWidget(self.page_pomiar_oporu)

#<------tryb ręczy--
        self.page_reczny = QtWidgets.QWidget()
        self.page_reczny.setObjectName("page_reczny")
        self.widget_20probek = QtWidgets.QWidget(self.page_reczny)
        self.widget_20probek.setGeometry(QtCore.QRect(40, 100, 681, 611))
        self.widget_20probek.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_20probek.setObjectName("widget_20probek")
        self.frame = QtWidgets.QFrame(self.page_reczny)
        self.frame.setGeometry(QtCore.QRect(730, 90, 431, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.frame_1 = QtWidgets.QFrame(self.frame)
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setLineWidth(3)
        self.label_1.setObjectName("label_1")
        self.gridLayout_4.addWidget(self.label_1, 0, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_1)
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout_4.addWidget(self.checkBox_1, 0, 1, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.frame_1)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_1, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_1, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(1)
        self.frame_11.setMidLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setLineWidth(3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_11, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_20.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_20.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setLineWidth(1)
        self.frame_12.setMidLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setLineWidth(3)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 0, 1, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.frame_12)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout.addWidget(self.comboBox_12, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_12, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setLineWidth(3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setLineWidth(1)
        self.frame_13.setMidLineWidth(0)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        self.label_13.setLineWidth(3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_14.addWidget(self.checkBox_13, 0, 1, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_13, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_13, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setLineWidth(3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_7.addWidget(self.checkBox_4, 0, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_4, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setLineWidth(1)
        self.frame_14.setMidLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setLineWidth(3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_14, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_14, 3, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_5, 0, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_19.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setLineWidth(3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_19.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setLineWidth(1)
        self.frame_15.setMidLineWidth(0)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_15, 0, 2, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_10.addWidget(self.checkBox_15, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setLineWidth(3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_15, 4, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_6, 0, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_15.addWidget(self.checkBox_6, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setLineWidth(3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setLineWidth(1)
        self.frame_16.setMidLineWidth(0)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setLineWidth(3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_16)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_8.addWidget(self.checkBox_16, 0, 1, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_16, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_16, 5, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(1)
        self.frame_7.setMidLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_7, 0, 2, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_18.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setLineWidth(3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_18.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_7, 6, 0, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setLineWidth(1)
        self.frame_17.setMidLineWidth(0)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setLineWidth(3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 0, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_17)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_11.addWidget(self.checkBox_17, 0, 1, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_17)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_17, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_17, 6, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_8, 0, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_17.addWidget(self.checkBox_8, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setLineWidth(3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_17.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_8, 7, 0, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_18.setLineWidth(1)
        self.frame_18.setMidLineWidth(0)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setLineWidth(3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_18)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_5.addWidget(self.checkBox_18, 0, 1, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_18)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_18, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_18, 7, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(1)
        self.frame_9.setMidLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_9, 0, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_16.addWidget(self.checkBox_9, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setLineWidth(3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_16.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_9, 8, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_19.setLineWidth(1)
        self.frame_19.setMidLineWidth(0)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_19)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_12.addWidget(self.checkBox_19, 0, 1, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_19)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_19, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setLineWidth(3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_19, 8, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setMidLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_10, 0, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_10)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_13.addWidget(self.checkBox_10, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setLineWidth(3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_10, 9, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_20.setLineWidth(1)
        self.frame_20.setMidLineWidth(0)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setLineWidth(3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_9.addWidget(self.checkBox_20, 0, 1, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_20)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_20, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_20, 9, 1, 1, 1)
        self.skala_reczny = QtWidgets.QCheckBox(self.page_reczny)
        self.skala_reczny.setGeometry(QtCore.QRect(40, 710, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.skala_reczny.setFont(font)
        self.skala_reczny.setObjectName("skala_reczny")
        self.label_czestotliwosc_2 = QtWidgets.QLabel(self.page_reczny)
        self.label_czestotliwosc_2.setGeometry(QtCore.QRect(730, 650, 180, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_czestotliwosc_2.setFont(font)
        self.label_czestotliwosc_2.setAcceptDrops(False)
        self.label_czestotliwosc_2.setAutoFillBackground(False)
        self.label_czestotliwosc_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_czestotliwosc_2.setWordWrap(True)
        self.label_czestotliwosc_2.setObjectName("label_czestotliwosc_2")
        self.doubleSpinBox_czestotliowsc_2 = QtWidgets.QDoubleSpinBox(self.page_reczny)
        self.doubleSpinBox_czestotliowsc_2.setGeometry(QtCore.QRect(910, 650, 62, 22))
        self.doubleSpinBox_czestotliowsc_2.setMinimum(2.0)
        self.doubleSpinBox_czestotliowsc_2.setMaximum(300.0)
        self.doubleSpinBox_czestotliowsc_2.setSingleStep(1.0)
        self.doubleSpinBox_czestotliowsc_2.setProperty("value", 3.0)
        self.doubleSpinBox_czestotliowsc_2.setObjectName("doubleSpinBox_czestotliowsc_2")
        self.doubleSpinBox_czestotliowsc_3 = QtWidgets.QDoubleSpinBox(self.page_reczny)
        self.doubleSpinBox_czestotliowsc_3.setGeometry(QtCore.QRect(910, 680, 62, 22))
        self.doubleSpinBox_czestotliowsc_3.setMinimum(2.0)
        self.doubleSpinBox_czestotliowsc_3.setMaximum(300.0)
        self.doubleSpinBox_czestotliowsc_3.setSingleStep(1.0)
        self.doubleSpinBox_czestotliowsc_3.setProperty("value", 3.0)
        self.doubleSpinBox_czestotliowsc_3.setObjectName("doubleSpinBox_czestotliowsc_3")
        self.label_czestotliwosc_3 = QtWidgets.QLabel(self.page_reczny)
        self.label_czestotliwosc_3.setGeometry(QtCore.QRect(730, 680, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_czestotliwosc_3.setFont(font)
        self.label_czestotliwosc_3.setAcceptDrops(False)
        self.label_czestotliwosc_3.setAutoFillBackground(False)
        self.label_czestotliwosc_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_czestotliwosc_3.setWordWrap(True)
        self.label_czestotliwosc_3.setObjectName("label_czestotliwosc_3")
        self.pushButton_start2 = QtWidgets.QPushButton(self.page_reczny)
        self.pushButton_start2.setGeometry(QtCore.QRect(1000, 650, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start2.setFont(font)
        self.pushButton_start2.setObjectName("pushButton_start2")
#-------------->

        self.stackedWidget.addWidget(self.page_reczny)
#<----zmiana trybu
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(910, 10, 243, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_tryb_opor = QtWidgets.QLabel(self.centralwidget)
        self.label_tryb_opor.setGeometry(QtCore.QRect(870, 10, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_tryb_opor.setFont(font)
        self.label_tryb_opor.setObjectName("label_tryb_opor")
#------>

#<-----nazwa pliku
        self.label_tytul2 = QtWidgets.QLabel(self.centralwidget)
        self.label_tytul2.setGeometry(QtCore.QRect(540, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_tytul2.setFont(font)
        self.label_tytul2.setObjectName("label_tytul2")

        self.nazwa_pliku = QtWidgets.QLineEdit(self.centralwidget)
        self.nazwa_pliku.setGeometry(QtCore.QRect(310, 10, 122, 26))
        self.nazwa_pliku.setObjectName("nazwa_pliku")


        self.label_wprowadz_nazwe = QtWidgets.QLabel(self.centralwidget)
        self.label_wprowadz_nazwe.setGeometry(QtCore.QRect(40, 10, 221, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wprowadz_nazwe.setFont(font)
        self.label_wprowadz_nazwe.setObjectName("label_wprowadz_nazwe")

        self.label_przedrostek = QtWidgets.QLabel(self.centralwidget)
        self.label_przedrostek.setGeometry(QtCore.QRect(213, 10, 90, 26))
        self.label_przedrostek.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_przedrostek.setFont(font)
        self.label_przedrostek.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_przedrostek.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_przedrostek.setObjectName("label_przedrostek")
#---------->

#<---pasek menu---
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menuUstawienia = QtWidgets.QMenu(self.menubar)
        self.menuUstawienia.setObjectName("menuUstawienia")
        self.menuPmoc = QtWidgets.QMenu(self.menubar)
        self.menuPmoc.setObjectName("menuPmoc")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuUstawienia.menuAction())
        self.menubar.addAction(self.menuPmoc.menuAction())
#------->


#<-----wykresy tryb 1--------------------------
        self.gridLayout_0 = QtWidgets.QGridLayout(self.widget_temp)
        self.gridLayout_0.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_0.setObjectName("gridLayout_1")
        self.wykres_1 = wykres.Wykres_temp(self.widget_temp, dpi=90)
        self.wykres_1.setObjectName("wykres_1")
        self.gridLayout_0.addWidget(self.wykres_1, 0, 0, 1, 1)

        self.gridLayout_1 = QtWidgets.QGridLayout(self.widget_probka1)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.wykres_2 = wykres.Wykres_probka(self.widget_probka1, dpi=90)
        self.wykres_2.setObjectName("wykres_2")
        self.gridLayout_1.addWidget(self.wykres_2, 0, 0, 1, 1)

        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_probka2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_1")
        self.wykres_3 = wykres.Wykres_probka(self.widget_probka2, dpi=90)
        self.wykres_3.setObjectName("wykres_3")
        self.gridLayout_2.addWidget(self.wykres_3, 0, 0, 1, 1)

#----------------------------------------->


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    #<---kanały, osie, wykresy--
        self.skala_temp.setText(_translate("MainWindow", "Skala log"))
        self.skala_probka1.setText(_translate("MainWindow", "Skala log"))
        self.skala_probka2.setText(_translate("MainWindow", "Skala log"))
        
        self.comboBox_kanaly1.setCurrentText(_translate("MainWindow", "brak"))
        self.comboBox_kanaly1.setItemText(0, _translate("MainWindow", "Kanał 1"))
        self.comboBox_kanaly1.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox_kanaly1.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox_kanaly1.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox_kanaly1.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox_kanaly1.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox_kanaly1.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox_kanaly1.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox_kanaly1.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox_kanaly1.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox_kanaly1.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox_kanaly1.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox_kanaly1.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox_kanaly1.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox_kanaly1.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox_kanaly1.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox_kanaly1.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox_kanaly1.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox_kanaly1.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox_kanaly1.setItemText(19, _translate("MainWindow", "Kanał 20"))

        self.comboBox_kanaly2.setItemText(0, _translate("MainWindow", "Kanał 1"))
        self.comboBox_kanaly2.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox_kanaly2.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox_kanaly2.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox_kanaly2.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox_kanaly2.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox_kanaly2.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox_kanaly2.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox_kanaly2.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox_kanaly2.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox_kanaly2.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox_kanaly2.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox_kanaly2.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox_kanaly2.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox_kanaly2.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox_kanaly2.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox_kanaly2.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox_kanaly2.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox_kanaly2.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox_kanaly2.setItemText(19, _translate("MainWindow", "Kanał 20"))

        self.comboBox_kanaly0.setCurrentText(_translate("MainWindow", "brak"))
        self.comboBox_kanaly0.setItemText(0, _translate("MainWindow", "Kanał 1"))
        self.comboBox_kanaly0.setItemText(1, _translate("MainWindow", "Kanał 2"))
        self.comboBox_kanaly0.setItemText(2, _translate("MainWindow", "Kanał 3"))
        self.comboBox_kanaly0.setItemText(3, _translate("MainWindow", "Kanał 4"))
        self.comboBox_kanaly0.setItemText(4, _translate("MainWindow", "Kanał 5"))
        self.comboBox_kanaly0.setItemText(5, _translate("MainWindow", "Kanał 6"))
        self.comboBox_kanaly0.setItemText(6, _translate("MainWindow", "Kanał 7"))
        self.comboBox_kanaly0.setItemText(7, _translate("MainWindow", "Kanał 8"))
        self.comboBox_kanaly0.setItemText(8, _translate("MainWindow", "Kanał 9"))
        self.comboBox_kanaly0.setItemText(9, _translate("MainWindow", "Kanał 10"))
        self.comboBox_kanaly0.setItemText(10, _translate("MainWindow", "Kanał 11"))
        self.comboBox_kanaly0.setItemText(11, _translate("MainWindow", "Kanał 12"))
        self.comboBox_kanaly0.setItemText(12, _translate("MainWindow", "Kanał 13"))
        self.comboBox_kanaly0.setItemText(13, _translate("MainWindow", "Kanał 14"))
        self.comboBox_kanaly0.setItemText(14, _translate("MainWindow", "Kanał 15"))
        self.comboBox_kanaly0.setItemText(15, _translate("MainWindow", "Kanał 16"))
        self.comboBox_kanaly0.setItemText(16, _translate("MainWindow", "Kanał 17"))
        self.comboBox_kanaly0.setItemText(17, _translate("MainWindow", "Kanał 18"))
        self.comboBox_kanaly0.setItemText(18, _translate("MainWindow", "Kanał 19"))
        self.comboBox_kanaly0.setItemText(19, _translate("MainWindow", "Kanał 20"))

        self.label_wybor1.setText(_translate("MainWindow", "Wybór kanału"))
        self.label_wybor2.setText(_translate("MainWindow", "Wybór kanału"))
        self.label_danex1.setText(_translate("MainWindow", "Dane osi X:"))
        self.comboBox_osx1.setItemText(0, _translate("MainWindow", "T [K]"))
        self.comboBox_osx1.setItemText(1, _translate("MainWindow", "t [s]"))
        self.label_danex2.setText(_translate("MainWindow", "Dane osi X:"))
        self.comboBox_osx2.setItemText(0, _translate("MainWindow", "T [K]"))
        self.comboBox_osx2.setItemText(1, _translate("MainWindow", "t [s]"))
        self.label_wybor1_2.setText(_translate("MainWindow", "Wybór kanału"))

    #---jeszcze cos--->
        self.label_automtyczne.setText(_translate("MainWindow", "Automatyczne śledzenie tempa przyrostu temperatury [K/min]"))
        self.label_srednie_tempo.setText(_translate("MainWindow", "0"))
        self.label_czestotliwosc.setText(_translate("MainWindow", "Częstotliwość próbkowania"))
        self.label_aktualna_moc_wartosc.setText(_translate("MainWindow", "0"))
        self.label_aktualna_temp.setText(_translate("MainWindow", "Aktualna temperatura:"))
        self.label_tempo.setText(_translate("MainWindow", "Średnie tempo przyrostu temperatury:"))
        self.label_aktualna_temp_wartosc.setText(_translate("MainWindow", "0"))
        self.label_aktualna_moc.setText(_translate("MainWindow", "Moc grzałki:"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
    #--------->
    #<----tryb reczny---    
        self.label_1.setText(_translate("MainWindow", "Kanał 1"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_11.setText(_translate("MainWindow", "Kanał 11"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_2.setText(_translate("MainWindow", "Kanał 2"))
        self.label_12.setText(_translate("MainWindow", "Kanał 12"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_3.setText(_translate("MainWindow", "Kanał 3"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_13.setText(_translate("MainWindow", "Kanał 13"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_4.setText(_translate("MainWindow", "Kanał 4"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_14.setText(_translate("MainWindow", "Kanał 14"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_5.setText(_translate("MainWindow", "Kanał 5"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_15.setText(_translate("MainWindow", "Kanał 15"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_6.setText(_translate("MainWindow", "Kanał 6"))
        self.label_16.setText(_translate("MainWindow", "Kanał 16"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_7.setText(_translate("MainWindow", "Kanał 7"))
        self.label_17.setText(_translate("MainWindow", "Kanał 17"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_8.setText(_translate("MainWindow", "Kanał 8"))
        self.label_18.setText(_translate("MainWindow", "Kanał 18"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_9.setText(_translate("MainWindow", "Kanał 9"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_19.setText(_translate("MainWindow", "Kanał 19"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_10.setText(_translate("MainWindow", "Kanał 10"))
        self.label_20.setText(_translate("MainWindow", "Kanał 20"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.skala_reczny.setText(_translate("MainWindow", "Skala log"))
        self.label_czestotliwosc_2.setText(_translate("MainWindow", "Okres między kanałami [s]"))
        self.label_czestotliwosc_3.setText(_translate("MainWindow", "Okres między seriami [s]"))
        self.pushButton_start2.setText(_translate("MainWindow", "Start"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pomiar oporu w funkcji temeperatury"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ręczny"))
        self.label_tryb_opor.setText(_translate("MainWindow", "Tryb: "))
        self.label_tytul2.setText(_translate("MainWindow", "Nazwa_pomiaru"))
        self.label_wprowadz_nazwe.setText(_translate("MainWindow", "Nazwa pliku wyjściowego:"))
        self.label_przedrostek.setText(_translate("MainWindow", self.data_pomiaru))
        self.menuUstawienia.setTitle(_translate("MainWindow", "Ustawienia"))
        self.menuPmoc.setTitle(_translate("MainWindow", "Pomoc"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())