from PyQt5 import QtCore, QtGui, QtWidgets

#<---------------------------
import matplotlib
matplotlib.use('Qt5Agg')        # używamy QT5

#----------------------->

#dla ułatwienia w pisaniu do nazw zmiennych i obiektów dodane zostały odpowiednie przedrostki:
# p2_ dla pomiaru dwóch próbek tak jak podczas standardowych ćwiczeń 
# r4_ dla pomiaru 4-punktowego (np. przy pomiarze nadprzewodnika)
# ch20_ dla trybu recznego w którym można będzie mierzyć w seri 20 próbek

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

    #<----glówne okno-----
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1180, 750))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setLineWidth(5)
        self.stackedWidget.setObjectName("stackedWidget")
    #-------------->

#<------tryb pomiar 2 próbek----
        self.P2_tryb = QtWidgets.QWidget()
        self.P2_tryb.setObjectName("P2_tryb")

    #<----obszary wykresów------
        self.P2_okno_wykresu_t = QtWidgets.QWidget(self.P2_tryb)
        self.P2_okno_wykresu_t.setGeometry(QtCore.QRect(40, 90, 450, 260))
        self.P2_okno_wykresu_t.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P2_okno_wykresu_t.setObjectName("P2_okno_wykresu_t")

        self.P2_okno_wykresu_p1 = QtWidgets.QWidget(self.P2_tryb)
        self.P2_okno_wykresu_p1.setGeometry(QtCore.QRect(40, 400, 530, 300))
        self.P2_okno_wykresu_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P2_okno_wykresu_p1.setObjectName("P2_okno_wykresu_p1")

        self.P2_okno_wykresu_p2 = QtWidgets.QWidget(self.P2_tryb)
        self.P2_okno_wykresu_p2.setGeometry(QtCore.QRect(610, 400, 530, 300))
        self.P2_okno_wykresu_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P2_okno_wykresu_p2.setObjectName("P2_okno_wykresu_p2")
    #---------------->

    #<-----czekboxy skala log----------
        self.P2_skala_log_t = QtWidgets.QCheckBox(self.P2_tryb)
        self.P2_skala_log_t.setGeometry(QtCore.QRect(50, 355, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_skala_log_t.setFont(font)
        self.P2_skala_log_t.setObjectName("P2_skala_log_t")

        self.P2_skala_log_p1 = QtWidgets.QCheckBox(self.P2_tryb)
        self.P2_skala_log_p1.setGeometry(QtCore.QRect(50, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_skala_log_p1.setFont(font)
        self.P2_skala_log_p1.setObjectName("P2_skala_log_p1")

        self.P2_skala_log_p2 = QtWidgets.QCheckBox(self.P2_tryb)
        self.P2_skala_log_p2.setGeometry(QtCore.QRect(620, 705, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_skala_log_p2.setFont(font)
        self.P2_skala_log_p2.setObjectName("P2_skala_log_p2")
    #---------------------->

    #<------kanały temeperatura----
        self.P2_wybor_kanalow_tekst_t = QtWidgets.QLabel(self.P2_tryb)
        self.P2_wybor_kanalow_tekst_t.setGeometry(QtCore.QRect(330, 355, 95, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_tekst_t.setFont(font)
        self.P2_wybor_kanalow_tekst_t.setObjectName("P2_wybor_kanalow_tekst_t")

        self.P2_wybor_kanalow_t = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_wybor_kanalow_t.setGeometry(QtCore.QRect(430, 355, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_t.setFont(font)
        self.P2_wybor_kanalow_t.setObjectName("P2_wybor_kanalow_t")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
        self.P2_wybor_kanalow_t.addItem("")
    #----------->
    #<---kanały probka 1-------------
        self.P2_wybor_kanalow_tekst_p1 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_wybor_kanalow_tekst_p1.setGeometry(QtCore.QRect(200, 705, 100, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_tekst_p1.setFont(font)
        self.P2_wybor_kanalow_tekst_p1.setObjectName("P2_wybor_kanalow_tekst_p1")

        self.P2_wybor_kanalow_p1= QtWidgets.QComboBox(self.P2_tryb)
        self.P2_wybor_kanalow_p1.setGeometry(QtCore.QRect(300, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_p1.setFont(font)
        self.P2_wybor_kanalow_p1.setObjectName("P2_wybor_kanalow_p1")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
        self.P2_wybor_kanalow_p1.addItem("")
    #----------->

    #<---------kanały próbka 2---------
        self.P2_wybor_kanalow_tekst_p2 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_wybor_kanalow_tekst_p2.setGeometry(QtCore.QRect(770, 705, 100, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_tekst_p2.setFont(font)
        self.P2_wybor_kanalow_tekst_p2.setObjectName("P2_wybor_kanalow_tekst_p2")

        self.P2_wybor_kanalow_p2 = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_wybor_kanalow_p2.setGeometry(QtCore.QRect(870, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_kanalow_p2.setFont(font)
        self.P2_wybor_kanalow_p2.setObjectName("P2_wybor_kanalow_p2")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
        self.P2_wybor_kanalow_p2.addItem("")
    #---------------->

    #------- osi----
        self.P2_wybor_osix_tekst_p1 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_wybor_osix_tekst_p1.setGeometry(QtCore.QRect(410, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_osix_tekst_p1.setFont(font)
        self.P2_wybor_osix_tekst_p1.setObjectName("P2_wybor_osix_tekst_p1")

        self.P2_wybor_osix_p1 = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_wybor_osix_p1.setGeometry(QtCore.QRect(490, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_osix_p1.setFont(font)
        self.P2_wybor_osix_p1.setObjectName("P2_wybor_osix_p1")
        self.P2_wybor_osix_p1.addItem("")
        self.P2_wybor_osix_p1.addItem("")


        self.P2_wybor_osix_tekst_p2 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_wybor_osix_tekst_p2.setGeometry(QtCore.QRect(980, 705, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_osix_tekst_p2.setFont(font)
        self.P2_wybor_osix_tekst_p2.setObjectName("P2_wybor_osix_tekst_p2")

        self.P2_wybor_osix_p2 = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_wybor_osix_p2.setGeometry(QtCore.QRect(1060, 705, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_wybor_osix_p2.setFont(font)
        self.P2_wybor_osix_p2.setObjectName("P2_wybor_osix_p2")
        self.P2_wybor_osix_p2.addItem("")
        self.P2_wybor_osix_p2.addItem("")

    #------------->

    #<-----start----

        self.P2_start = QtWidgets.QPushButton(self.P2_tryb)
        self.P2_start.setGeometry(QtCore.QRect(970, 240, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.P2_start.setFont(font)
        self.P2_start.setObjectName("P2_start")

        self.P2_reset = QtWidgets.QPushButton(self.P2_tryb)
        self.P2_reset.setGeometry(QtCore.QRect(970, 300, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.P2_reset.setFont(font)
        self.P2_reset.setObjectName("P2_reset")

        self.P2_licznik = QtWidgets.QLabel(self.P2_tryb)
        self.P2_licznik.setGeometry(QtCore.QRect(970, 199, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_licznik.setFont(font)
        self.P2_licznik.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P2_licznik.setFrameShape(QtWidgets.QFrame.Panel)
        self.P2_licznik.setFrameShadow(QtWidgets.QFrame.Raised)
        self.P2_licznik.setAlignment(QtCore.Qt.AlignCenter)
        self.P2_licznik.setObjectName("P2_licznik")
    #-------------->

    #<----czestotliwość-----
        self.P2_czestotliowsc = QtWidgets.QDoubleSpinBox(self.P2_tryb)
        self.P2_czestotliowsc.setGeometry(QtCore.QRect(800, 208, 65, 22))
        self.P2_czestotliowsc.setMinimum(5.0)
        self.P2_czestotliowsc.setMaximum(300.0)
        self.P2_czestotliowsc.setSingleStep(1.0)
        self.P2_czestotliowsc.setProperty("value", 5.0)
        self.P2_czestotliowsc.setObjectName("P2_czestotliowsc")
        
        self.P2_czestotliowsc_tekst = QtWidgets.QLabel(self.P2_tryb)
        self.P2_czestotliowsc_tekst.setGeometry(QtCore.QRect(540, 210, 201, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.P2_czestotliowsc_tekst.setFont(font)
        self.P2_czestotliowsc_tekst.setAcceptDrops(False)
        self.P2_czestotliowsc_tekst.setAutoFillBackground(False)
        self.P2_czestotliowsc_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.P2_czestotliowsc_tekst.setWordWrap(True)
        self.P2_czestotliowsc_tekst.setObjectName("P2_czestotliowsc_tekst")
    #------------>

    #<--------automatycznie śledzenie i tempo
        self.P2_tempo = QtWidgets.QLabel(self.P2_tryb)
        self.P2_tempo.setGeometry(QtCore.QRect(850-32, 258, 48, 18))
        self.P2_tempo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_tempo.setFont(font)
        self.P2_tempo.setObjectName("P2_tempo")

        self.P2_tempo_tekst = QtWidgets.QLabel(self.P2_tryb)
        self.P2_tempo_tekst.setGeometry(QtCore.QRect(540, 250, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.P2_tempo_tekst.setFont(font)
        self.P2_tempo_tekst.setAcceptDrops(False)
        self.P2_tempo_tekst.setAutoFillBackground(False)
        self.P2_tempo_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.P2_tempo_tekst.setWordWrap(True)
        self.P2_tempo_tekst.setObjectName("P2_tempo_tekst")


        self.P2_sledzenie_temp_tekst = QtWidgets.QLabel(self.P2_tryb)
        self.P2_sledzenie_temp_tekst.setGeometry(QtCore.QRect(540, 306, 209, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.P2_sledzenie_temp_tekst.setFont(font)
        self.P2_sledzenie_temp_tekst.setAcceptDrops(False)
        self.P2_sledzenie_temp_tekst.setAutoFillBackground(False)
        self.P2_sledzenie_temp_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.P2_sledzenie_temp_tekst.setWordWrap(True)
        self.P2_sledzenie_temp_tekst.setObjectName("P2_sledzenie_temp_tekst")

        self.P2_sledzenie_temp_wartosc = QtWidgets.QDoubleSpinBox(self.P2_tryb)
        self.P2_sledzenie_temp_wartosc.setGeometry(QtCore.QRect(800, 311, 70, 22))
        self.P2_sledzenie_temp_wartosc.setMinimum(80.0)
        self.P2_sledzenie_temp_wartosc.setMaximum(300.0)
        self.P2_sledzenie_temp_wartosc.setProperty("value", 250.0)
        self.P2_sledzenie_temp_wartosc.setObjectName("P2_sledzenie_temp_wartosc")

        self.P2_sledzenie_temp_okienko = QtWidgets.QCheckBox(self.P2_tryb)
        self.P2_sledzenie_temp_okienko.setGeometry(QtCore.QRect(750, 310, 16, 16))
        self.P2_sledzenie_temp_okienko.setText("")
        self.P2_sledzenie_temp_okienko.setObjectName("P2_sledzenie_temp_okienko")
    #-------------->

    #<---temeperatura-----
        self.P2_temperatura_tekst = QtWidgets.QLabel(self.P2_tryb)
        self.P2_temperatura_tekst.setGeometry(QtCore.QRect(540, 170, 190, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_temperatura_tekst.setFont(font)
        self.P2_temperatura_tekst.setObjectName("P2_temperatura_tekst")

        self.P2_temperatura= QtWidgets.QLabel(self.P2_tryb)
        self.P2_temperatura.setGeometry(QtCore.QRect(850-32, 170, 48, 18))
        self.P2_temperatura.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_temperatura.setFont(font)
        self.P2_temperatura.setObjectName("P2_temperatura")
    #-------->
    
    #<---------moc-----
        self.P2_moc_tekst = QtWidgets.QLabel(self.P2_tryb)
        self.P2_moc_tekst.setGeometry(QtCore.QRect(540, 130, 120, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_moc_tekst.setFont(font)
        self.P2_moc_tekst.setObjectName("P2_moc_tekst")

        self.P2_moc = QtWidgets.QLabel(self.P2_tryb)
        self.P2_moc.setGeometry(QtCore.QRect(850-32, 130, 48, 18))
        self.P2_moc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_moc.setFont(font)
        self.P2_moc.setObjectName("P2_moc")

        self.P2_moc_suwak = QtWidgets.QSlider(self.P2_tryb)
        self.P2_moc_suwak.setGeometry(QtCore.QRect(910, 128, 191, 22))
        self.P2_moc_suwak.setOrientation(QtCore.Qt.Horizontal)
        self.P2_moc_suwak.setObjectName("P2_moc_suwak")
        self.P2_moc_suwak.setMinimum(0)
        self.P2_moc_suwak.setMaximum(100)
        self.P2_moc_suwak.setSingleStep(1)
        self.P2_moc_suwak.setProperty("value",0)
    #----->

    #<---zakresy-------------
        self.P2_zakres_tekst_p1 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_zakres_tekst_p1.setGeometry(QtCore.QRect(200, 730, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_zakres_tekst_p1.setFont(font)
        self.P2_zakres_tekst_p1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.P2_zakres_tekst_p1.setObjectName("P2_zakres_tekst_p1")
        self.P2_zakres_p1 = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_zakres_p1.setGeometry(QtCore.QRect(300, 730, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_zakres_p1.setFont(font)
        self.P2_zakres_p1.setObjectName("P2_zakres_p1")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")
        self.P2_zakres_p1.addItem("")

        self.P2_zakres_tekst_p2 = QtWidgets.QLabel(self.P2_tryb)
        self.P2_zakres_tekst_p2.setGeometry(QtCore.QRect(770, 730, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_zakres_tekst_p2.setFont(font)
        self.P2_zakres_tekst_p2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.P2_zakres_tekst_p2.setObjectName("P2_zakres_tekst_p2")
        self.P2_zakres_p2 = QtWidgets.QComboBox(self.P2_tryb)
        self.P2_zakres_p2.setGeometry(QtCore.QRect(870, 730, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.P2_zakres_p2.setFont(font)
        self.P2_zakres_p2.setObjectName("P2_zakres_p2")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
        self.P2_zakres_p2.addItem("")
    #---------->
        self.stackedWidget.addWidget(self.P2_tryb)
#----------------->

#<------------tryb 4-punktowy----
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("pomiar_4pkt")
        
    #<-----tempo i sledzenie temperatury-----------
        self.R4_temperatura_tekst = QtWidgets.QLabel(self.page)
        self.R4_temperatura_tekst.setGeometry(QtCore.QRect(750, 470, 181, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_temperatura_tekst.setFont(font)
        self.R4_temperatura_tekst.setObjectName("R4_temperatura_tekst")

        self.R4_temperatura = QtWidgets.QLabel(self.page)
        self.R4_temperatura.setGeometry(QtCore.QRect(1050, 470, 65, 18))
        self.R4_temperatura.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_temperatura.setFont(font)
        self.R4_temperatura.setObjectName("R4_temperatura")

        self.R4_tempo_tekst = QtWidgets.QLabel(self.page)
        self.R4_tempo_tekst.setGeometry(QtCore.QRect(750, 550, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.R4_tempo_tekst.setFont(font)
        self.R4_tempo_tekst.setAcceptDrops(False)
        self.R4_tempo_tekst.setAutoFillBackground(False)
        self.R4_tempo_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.R4_tempo_tekst.setWordWrap(True)
        self.R4_tempo_tekst.setObjectName("R4_tempo_tekst")

        self.R4_tempo = QtWidgets.QLabel(self.page)
        self.R4_tempo.setGeometry(QtCore.QRect(1050, 558, 65, 18))
        self.R4_tempo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_tempo.setFont(font)
        self.R4_tempo.setObjectName("R4_tempo")

        self.R4_sledzenie_temp_tekst = QtWidgets.QLabel(self.page)
        self.R4_sledzenie_temp_tekst.setGeometry(QtCore.QRect(750, 606, 209, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.R4_sledzenie_temp_tekst.setFont(font)
        self.R4_sledzenie_temp_tekst.setAcceptDrops(False)
        self.R4_sledzenie_temp_tekst.setAutoFillBackground(False)
        self.R4_sledzenie_temp_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.R4_sledzenie_temp_tekst.setWordWrap(True)
        self.R4_sledzenie_temp_tekst.setObjectName("R4_sledzenie_temp_tekst")

        self.R4_sledzenie_temp_okienko = QtWidgets.QCheckBox(self.page)
        self.R4_sledzenie_temp_okienko.setGeometry(QtCore.QRect(920, 610, 16, 16))
        self.R4_sledzenie_temp_okienko.setText("")
        self.R4_sledzenie_temp_okienko.setObjectName("R4_sledzenie_temp_okienko")
    
        self.R4_sledzenie_temp_wartosc = QtWidgets.QDoubleSpinBox(self.page)
        self.R4_sledzenie_temp_wartosc.setGeometry(QtCore.QRect(1050, 611, 65, 22))
        self.R4_sledzenie_temp_wartosc.setMinimum(-100.0)
        self.R4_sledzenie_temp_wartosc.setMaximum(100.0)
        self.R4_sledzenie_temp_wartosc.setProperty("value", 1.0)
        self.R4_sledzenie_temp_wartosc.setObjectName("R4_sledzenie_temp_wartosc")        
    #------------>

    #<----okna wykresów------
        self.R4_okno_wykresu_t = QtWidgets.QWidget(self.page)
        self.R4_okno_wykresu_t.setGeometry(QtCore.QRect(730, 80, 410, 260))
        self.R4_okno_wykresu_t.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.R4_okno_wykresu_t.setObjectName("R4_okno_wykresu_t")

        self.R4_okno_wykresu_p = QtWidgets.QWidget(self.page)
        self.R4_okno_wykresu_p.setGeometry(QtCore.QRect(40, 81, 660, 620))
        self.R4_okno_wykresu_p.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.R4_okno_wykresu_p.setObjectName("R4_okno_wykresu_p")
    #------------->

    #<-----kanały próbka----------
        self.R4_wybor_kanalow_tekst_p = QtWidgets.QLabel(self.page)
        self.R4_wybor_kanalow_tekst_p.setGeometry(QtCore.QRect(200, 710, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_kanalow_tekst_p.setFont(font)
        self.R4_wybor_kanalow_tekst_p.setObjectName("R4_wybor_kanalow_tekst_p")
        
        self.R4_wybor_kanalow_p = QtWidgets.QComboBox(self.page)
        self.R4_wybor_kanalow_p.setGeometry(QtCore.QRect(300, 710, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_kanalow_p.setFont(font)
        self.R4_wybor_kanalow_p.setObjectName("R4_wybor_kanalow_p")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
        self.R4_wybor_kanalow_p.addItem("")
    #------------>

    #<------wybór osi------   
        self.R4_wybor_osix_tekst_p = QtWidgets.QLabel(self.page)
        self.R4_wybor_osix_tekst_p.setGeometry(QtCore.QRect(550, 710, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_osix_tekst_p.setFont(font)
        self.R4_wybor_osix_tekst_p.setObjectName("R4_wybor_osix_tekst_p")

        self.R4_wybor_osix_p = QtWidgets.QComboBox(self.page)
        self.R4_wybor_osix_p.setGeometry(QtCore.QRect(630, 710, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_osix_p.setFont(font)
        self.R4_wybor_osix_p.setObjectName("R4_wybor_osix_p")
        self.R4_wybor_osix_p.addItem("")
        self.R4_wybor_osix_p.addItem("")
    #-------------------------

    #<-------zakres-------

        self.R4_zakres_tekst = QtWidgets.QLabel(self.page)
        self.R4_zakres_tekst.setGeometry(QtCore.QRect(340, 710, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_zakres_tekst.setFont(font)
        self.R4_zakres_tekst.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R4_zakres_tekst.setObjectName("R4_zakres_tekst")

        self.R4_zakres_p = QtWidgets.QComboBox(self.page)
        self.R4_zakres_p.setGeometry(QtCore.QRect(440, 710, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_zakres_p.setFont(font)
        self.R4_zakres_p.setObjectName("R4_zakres_p")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
        self.R4_zakres_p.addItem("")
    #------------------>

    #<------skala log------
        self.R4_skala_log_p = QtWidgets.QCheckBox(self.page)
        self.R4_skala_log_p.setGeometry(QtCore.QRect(50, 710, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_skala_log_p.setFont(font)
        self.R4_skala_log_p.setObjectName("R4_skala_log_p")
        
        self.R4_skala_log_t = QtWidgets.QCheckBox(self.page)
        self.R4_skala_log_t.setGeometry(QtCore.QRect(740, 340, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_skala_log_t.setFont(font)
        self.R4_skala_log_t.setObjectName("R4_skala_log_t")
    #---------------
    
    #<-----czestotliowsc--------
        self.R4_czestotliowsc_tekst = QtWidgets.QLabel(self.page)
        self.R4_czestotliowsc_tekst.setGeometry(QtCore.QRect(750, 510, 200, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.R4_czestotliowsc_tekst.setFont(font)
        self.R4_czestotliowsc_tekst.setAcceptDrops(False)
        self.R4_czestotliowsc_tekst.setAutoFillBackground(False)
        self.R4_czestotliowsc_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.R4_czestotliowsc_tekst.setWordWrap(True)
        self.R4_czestotliowsc_tekst.setObjectName("R4_czestotliowsc_tekst")

        self.R4_czestotliowsc = QtWidgets.QDoubleSpinBox(self.page)
        self.R4_czestotliowsc.setGeometry(QtCore.QRect(1050, 508, 65, 22))
        self.R4_czestotliowsc.setMinimum(5.0)
        self.R4_czestotliowsc.setMaximum(300.0)
        self.R4_czestotliowsc.setSingleStep(1.0)
        self.R4_czestotliowsc.setProperty("value", 5.0)
        self.R4_czestotliowsc.setObjectName("R4_czestotliowsc")
    #--------------->
    
    #<------moc------------
        self.R4_moc_tekst = QtWidgets.QLabel(self.page)
        self.R4_moc_tekst.setGeometry(QtCore.QRect(750, 400, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_moc_tekst.setFont(font)
        self.R4_moc_tekst.setObjectName("R4_moc_tekst")

        self.R4_moc_suwak = QtWidgets.QSlider(self.page)
        self.R4_moc_suwak.setGeometry(QtCore.QRect(750, 430, 370, 22))
        self.R4_moc_suwak.setOrientation(QtCore.Qt.Horizontal)
        self.R4_moc_suwak.setObjectName("R4_moc_suwak")
        self.R4_moc_suwak.setMinimum(0)
        self.R4_moc_suwak.setMaximum(100)
        self.R4_moc_suwak.setSingleStep(1)
        self.R4_moc_suwak.setProperty("value",0)
    
        self.R4_moc = QtWidgets.QLabel(self.page)
        self.R4_moc.setGeometry(QtCore.QRect(1050, 400, 65, 18))
        self.R4_moc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_moc.setFont(font)
        self.R4_moc.setObjectName("R4_moc")
    #---------------->

    #<---kanały temp------        
        self.R4_wybor_kanalow_tekst_t = QtWidgets.QLabel(self.page)
        self.R4_wybor_kanalow_tekst_t.setGeometry(QtCore.QRect(990, 340, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_kanalow_tekst_t.setFont(font)
        self.R4_wybor_kanalow_tekst_t.setObjectName("R4_wybor_kanalow_tekst_t")

        self.R4_wybor_kanalow_t = QtWidgets.QComboBox(self.page)
        self.R4_wybor_kanalow_t.setGeometry(QtCore.QRect(1090, 340, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_wybor_kanalow_t.setFont(font)
        self.R4_wybor_kanalow_t.setObjectName("R4_wybor_kanalow_t")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
        self.R4_wybor_kanalow_t.addItem("")
    #----------------->

    #<------wybór osi----

    #<------start-----------        
        self.R4_start = QtWidgets.QPushButton(self.page)
        self.R4_start.setGeometry(QtCore.QRect(750, 670, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R4_start.setFont(font)
        self.R4_start.setObjectName("R4_start")

        self.R4_reset = QtWidgets.QPushButton(self.page)
        self.R4_reset.setGeometry(QtCore.QRect(990, 700, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.R4_reset.setFont(font)
        self.R4_reset.setObjectName("R4_reset")
        
        self.R4_licznik = QtWidgets.QLabel(self.page)
        self.R4_licznik.setGeometry(QtCore.QRect(990, 670, 131, 26))
        self.R4_licznik.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R4_licznik.setFont(font)
        self.R4_licznik.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.R4_licznik.setFrameShape(QtWidgets.QFrame.Panel)
        self.R4_licznik.setFrameShadow(QtWidgets.QFrame.Raised)
        self.R4_licznik.setAlignment(QtCore.Qt.AlignCenter)
        self.R4_licznik.setObjectName("R4_licznik")
    #---------------->
        self.stackedWidget.addWidget(self.page)
#---------------------------->

#<------tryb ręczy--
        self.Tryb_CH20 = QtWidgets.QWidget()
        self.Tryb_CH20.setObjectName("Tryb_CH20")

    #<---------okno wykresu----
        self.CH20_okno_wykresu = QtWidgets.QWidget(self.Tryb_CH20)
        self.CH20_okno_wykresu.setGeometry(QtCore.QRect(40, 80, 680, 630))
        self.CH20_okno_wykresu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CH20_okno_wykresu.setObjectName("CH20_okno_wykresu")
    #---------------->

    #<--------skala log-----------
        self.CH20_skala_log = QtWidgets.QCheckBox(self.Tryb_CH20)
        self.CH20_skala_log.setGeometry(QtCore.QRect(40, 710, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CH20_skala_log.setFont(font)
        self.CH20_skala_log.setObjectName("CH20_skala_log")
    #------------>

    #<-------czestotliwości----
        self.CH20_czestotliowsc_in_tekst = QtWidgets.QLabel(self.Tryb_CH20)
        self.CH20_czestotliowsc_in_tekst.setGeometry(QtCore.QRect(730, 615, 180, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.CH20_czestotliowsc_in_tekst.setFont(font)
        self.CH20_czestotliowsc_in_tekst.setAcceptDrops(False)
        self.CH20_czestotliowsc_in_tekst.setAutoFillBackground(False)
        self.CH20_czestotliowsc_in_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.CH20_czestotliowsc_in_tekst.setWordWrap(True)
        self.CH20_czestotliowsc_in_tekst.setObjectName("CH20_czestotliowsc_in_tekst")

        self.CH20_czestotliowsc_in = QtWidgets.QDoubleSpinBox(self.Tryb_CH20)
        self.CH20_czestotliowsc_in.setGeometry(QtCore.QRect(920, 615, 62, 22))
        self.CH20_czestotliowsc_in.setMinimum(2.0)
        self.CH20_czestotliowsc_in.setMaximum(300.0)
        self.CH20_czestotliowsc_in.setSingleStep(1.0)
        self.CH20_czestotliowsc_in.setProperty("value", 3.0)
        self.CH20_czestotliowsc_in.setObjectName("CH20_czestotliowsc_in")

        self.CH20_czestotliowsc_out_tekst = QtWidgets.QLabel(self.Tryb_CH20)
        self.CH20_czestotliowsc_out_tekst.setGeometry(QtCore.QRect(730, 650, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.CH20_czestotliowsc_out_tekst.setFont(font)
        self.CH20_czestotliowsc_out_tekst.setAcceptDrops(False)
        self.CH20_czestotliowsc_out_tekst.setAutoFillBackground(False)
        self.CH20_czestotliowsc_out_tekst.setTextFormat(QtCore.Qt.AutoText)
        self.CH20_czestotliowsc_out_tekst.setWordWrap(True)
        self.CH20_czestotliowsc_out_tekst.setObjectName("CH20_czestotliowsc_out_tekst")

        self.CH20_czestotliowsc_out = QtWidgets.QDoubleSpinBox(self.Tryb_CH20)
        self.CH20_czestotliowsc_out.setGeometry(QtCore.QRect(920, 650, 62, 22))
        self.CH20_czestotliowsc_out.setMinimum(5.0)
        self.CH20_czestotliowsc_out.setMaximum(300.0)
        self.CH20_czestotliowsc_out.setSingleStep(1.0)
        self.CH20_czestotliowsc_out.setProperty("value", 10.0)
        self.CH20_czestotliowsc_out.setObjectName("CH20_czestotliowsc_out")
    #------------------------->

    #<-----start
        self.CH20_start = QtWidgets.QPushButton(self.Tryb_CH20)
        self.CH20_start.setGeometry(QtCore.QRect(1000, 615, 150, 55))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CH20_start.setFont(font)
        self.CH20_start.setObjectName("CH20_start")

        self.CH20_reset = QtWidgets.QPushButton(self.Tryb_CH20)
        self.CH20_reset.setGeometry(QtCore.QRect(1000, 675, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CH20_reset.setFont(font)
        self.CH20_reset.setObjectName("R4_reset")
        
        self.CH20_licznik = QtWidgets.QLabel(self.Tryb_CH20)
        self.CH20_licznik.setGeometry(QtCore.QRect(920, 685, 62, 25))
        self.CH20_licznik.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CH20_licznik.setFont(font)
        self.CH20_licznik.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CH20_licznik.setFrameShape(QtWidgets.QFrame.Panel)
        self.CH20_licznik.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CH20_licznik.setAlignment(QtCore.Qt.AlignCenter)
        self.CH20_licznik.setObjectName("R4_licznik")
    #---------

    #<----wybór kanałów i rodzaju pomiaru----------    
        self.frame = QtWidgets.QFrame(self.Tryb_CH20)
        self.frame.setGeometry(QtCore.QRect(730, 70, 431, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.frame_1 = QtWidgets.QFrame(self.frame)
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setLineWidth(3)
        self.label_1.setObjectName("label_1")
        self.gridLayout_4.addWidget(self.label_1, 0, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_1)
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout_4.addWidget(self.checkBox_1, 0, 1, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.frame_1)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_1, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_1, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(1)
        self.frame_11.setMidLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setLineWidth(3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_11, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_20.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_20.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setLineWidth(1)
        self.frame_12.setMidLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setLineWidth(3)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 0, 1, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.frame_12)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout.addWidget(self.comboBox_12, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_12, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setLineWidth(3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setLineWidth(1)
        self.frame_13.setMidLineWidth(0)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        self.label_13.setLineWidth(3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_14.addWidget(self.checkBox_13, 0, 1, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_13, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_13, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setLineWidth(3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_7.addWidget(self.checkBox_4, 0, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_4, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setLineWidth(1)
        self.frame_14.setMidLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setLineWidth(3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_14, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_14, 3, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_5, 0, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_19.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setLineWidth(3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_19.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setLineWidth(1)
        self.frame_15.setMidLineWidth(0)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_15, 0, 2, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_10.addWidget(self.checkBox_15, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setLineWidth(3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_15, 4, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_6, 0, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_15.addWidget(self.checkBox_6, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setLineWidth(3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setLineWidth(1)
        self.frame_16.setMidLineWidth(0)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setLineWidth(3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_16)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_8.addWidget(self.checkBox_16, 0, 1, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_16, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_16, 5, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(1)
        self.frame_7.setMidLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_7, 0, 2, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_18.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setLineWidth(3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_18.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_7, 6, 0, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setLineWidth(1)
        self.frame_17.setMidLineWidth(0)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setLineWidth(3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 0, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_17)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_11.addWidget(self.checkBox_17, 0, 1, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_17)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_17, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_17, 6, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_8, 0, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_17.addWidget(self.checkBox_8, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setLineWidth(3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_17.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_8, 7, 0, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_18.setLineWidth(1)
        self.frame_18.setMidLineWidth(0)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setLineWidth(3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_18)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_5.addWidget(self.checkBox_18, 0, 1, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_18)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_18, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_18, 7, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(1)
        self.frame_9.setMidLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_9, 0, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_16.addWidget(self.checkBox_9, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setLineWidth(3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_16.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_9, 8, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_19.setLineWidth(1)
        self.frame_19.setMidLineWidth(0)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_19)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_12.addWidget(self.checkBox_19, 0, 1, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_19)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_19, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setLineWidth(3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_19, 8, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setMidLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_10, 0, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_10)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_13.addWidget(self.checkBox_10, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setLineWidth(3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.frame_10, 9, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_20.setLineWidth(1)
        self.frame_20.setMidLineWidth(0)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setLineWidth(3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_9.addWidget(self.checkBox_20, 0, 1, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_20)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_20, 0, 2, 1, 1)
        self.gridLayout_41.addWidget(self.frame_20, 9, 1, 1, 1)
    #---------

#-------------->
        self.stackedWidget.addWidget(self.Tryb_CH20)

#<----zmiana trybu

        self.zmiana_trybu = QtWidgets.QComboBox(self.centralwidget)
        self.zmiana_trybu.setGeometry(QtCore.QRect(910, 10, 243, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.zmiana_trybu.setFont(font)
        self.zmiana_trybu.setObjectName("zmiana_trybu")
        self.zmiana_trybu.addItem("")
        self.zmiana_trybu.addItem("")
        self.zmiana_trybu.addItem("")

        self.zmiana_trybu_tekst = QtWidgets.QLabel(self.centralwidget)
        self.zmiana_trybu_tekst.setGeometry(QtCore.QRect(870, 10, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.zmiana_trybu_tekst.setFont(font)
        self.zmiana_trybu_tekst.setObjectName("zmiana_trybu_tekst")
#------>

#<-----nazwa pliku
        self.naglowek = QtWidgets.QLabel(self.centralwidget)
        self.naglowek.setGeometry(QtCore.QRect(540, 10, 250, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.naglowek.setFont(font)
        self.naglowek.setObjectName("naglowek")

        self.nazwa_pliku = QtWidgets.QLineEdit(self.centralwidget)
        self.nazwa_pliku.setGeometry(QtCore.QRect(310, 10, 122, 26))
        self.nazwa_pliku.setObjectName("nazwa_pliku")

        self.nazwa_pliku_tekst = QtWidgets.QLabel(self.centralwidget)
        self.nazwa_pliku_tekst.setGeometry(QtCore.QRect(40, 10, 221, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nazwa_pliku_tekst.setFont(font)
        self.nazwa_pliku_tekst.setObjectName("nazwa_pliku_tekst")

        self.nazwa_pliku_przedrostek = QtWidgets.QLabel(self.centralwidget)
        self.nazwa_pliku_przedrostek.setGeometry(QtCore.QRect(213, 10, 90, 26))
        self.nazwa_pliku_przedrostek.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nazwa_pliku_przedrostek.setFont(font)
        self.nazwa_pliku_przedrostek.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nazwa_pliku_przedrostek.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nazwa_pliku_przedrostek.setObjectName("nazwa_pliku_przedrostek")
#---------->

#<---pasek menu---
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(MainWindow)
        self.menu.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menu.setObjectName("menu")
        self.Ustawienia = QtWidgets.QAction(self.menu)
        self.Ustawienia.setObjectName("Ustawienia")
        self.Pomoc = QtWidgets.QAction(self.menu)
        self.Pomoc.setObjectName("Pomoc")
        MainWindow.setMenuBar(self.menu)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu.addAction(self.Ustawienia)
        self.menu.addAction(self.Pomoc)
#------->

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    #<---pomiar 2 próbek--
        self.P2_skala_log_t.setText(_translate("MainWindow", "Skala log"))
        self.P2_skala_log_p1.setText(_translate("MainWindow", "Skala log"))
        self.P2_skala_log_p2.setText(_translate("MainWindow", "Skala log"))
        
        self.P2_wybor_kanalow_p1.setCurrentText(_translate("MainWindow", "2"))
        self.P2_wybor_kanalow_p1.setItemText(0, _translate("MainWindow", "1"))
        self.P2_wybor_kanalow_p1.setItemText(1, _translate("MainWindow", "2"))
        self.P2_wybor_kanalow_p1.setItemText(2, _translate("MainWindow", "3"))
        self.P2_wybor_kanalow_p1.setItemText(3, _translate("MainWindow", "4"))
        self.P2_wybor_kanalow_p1.setItemText(4, _translate("MainWindow", "5"))
        self.P2_wybor_kanalow_p1.setItemText(5, _translate("MainWindow", "6"))
        self.P2_wybor_kanalow_p1.setItemText(6, _translate("MainWindow", "7"))
        self.P2_wybor_kanalow_p1.setItemText(7, _translate("MainWindow", "8"))
        self.P2_wybor_kanalow_p1.setItemText(8, _translate("MainWindow", "9"))
        self.P2_wybor_kanalow_p1.setItemText(9, _translate("MainWindow", "10"))
        self.P2_wybor_kanalow_p1.setItemText(10, _translate("MainWindow", "11"))
        self.P2_wybor_kanalow_p1.setItemText(11, _translate("MainWindow", "12"))
        self.P2_wybor_kanalow_p1.setItemText(12, _translate("MainWindow", "13"))
        self.P2_wybor_kanalow_p1.setItemText(13, _translate("MainWindow", "14"))
        self.P2_wybor_kanalow_p1.setItemText(14, _translate("MainWindow", "15"))
        self.P2_wybor_kanalow_p1.setItemText(15, _translate("MainWindow", "16"))
        self.P2_wybor_kanalow_p1.setItemText(16, _translate("MainWindow", "17"))
        self.P2_wybor_kanalow_p1.setItemText(17, _translate("MainWindow", "18"))
        self.P2_wybor_kanalow_p1.setItemText(18, _translate("MainWindow", "19"))
        self.P2_wybor_kanalow_p1.setItemText(19, _translate("MainWindow", "20"))

        self.P2_wybor_kanalow_p2.setCurrentText(_translate("MainWindow", "3"))
        self.P2_wybor_kanalow_p2.setItemText(0, _translate("MainWindow", "1"))
        self.P2_wybor_kanalow_p2.setItemText(1, _translate("MainWindow", "2"))
        self.P2_wybor_kanalow_p2.setItemText(2, _translate("MainWindow", "3"))
        self.P2_wybor_kanalow_p2.setItemText(3, _translate("MainWindow", "4"))
        self.P2_wybor_kanalow_p2.setItemText(4, _translate("MainWindow", "5"))
        self.P2_wybor_kanalow_p2.setItemText(5, _translate("MainWindow", "6"))
        self.P2_wybor_kanalow_p2.setItemText(6, _translate("MainWindow", "7"))
        self.P2_wybor_kanalow_p2.setItemText(7, _translate("MainWindow", "8"))
        self.P2_wybor_kanalow_p2.setItemText(8, _translate("MainWindow", "9"))
        self.P2_wybor_kanalow_p2.setItemText(9, _translate("MainWindow", "10"))
        self.P2_wybor_kanalow_p2.setItemText(10, _translate("MainWindow", "11"))
        self.P2_wybor_kanalow_p2.setItemText(11, _translate("MainWindow", "12"))
        self.P2_wybor_kanalow_p2.setItemText(12, _translate("MainWindow", "13"))
        self.P2_wybor_kanalow_p2.setItemText(13, _translate("MainWindow", "14"))
        self.P2_wybor_kanalow_p2.setItemText(14, _translate("MainWindow", "15"))
        self.P2_wybor_kanalow_p2.setItemText(15, _translate("MainWindow", "16"))
        self.P2_wybor_kanalow_p2.setItemText(16, _translate("MainWindow", "17"))
        self.P2_wybor_kanalow_p2.setItemText(17, _translate("MainWindow", "18"))
        self.P2_wybor_kanalow_p2.setItemText(18, _translate("MainWindow", "19"))
        self.P2_wybor_kanalow_p2.setItemText(19, _translate("MainWindow", "20"))

        self.P2_wybor_kanalow_t.setCurrentText(_translate("MainWindow", "1"))
        self.P2_wybor_kanalow_t.setItemText(0, _translate("MainWindow", "1"))
        self.P2_wybor_kanalow_t.setItemText(1, _translate("MainWindow", "2"))
        self.P2_wybor_kanalow_t.setItemText(2, _translate("MainWindow", "3"))
        self.P2_wybor_kanalow_t.setItemText(3, _translate("MainWindow", "4"))
        self.P2_wybor_kanalow_t.setItemText(4, _translate("MainWindow", "5"))
        self.P2_wybor_kanalow_t.setItemText(5, _translate("MainWindow", "6"))
        self.P2_wybor_kanalow_t.setItemText(6, _translate("MainWindow", "7"))
        self.P2_wybor_kanalow_t.setItemText(7, _translate("MainWindow", "8"))
        self.P2_wybor_kanalow_t.setItemText(8, _translate("MainWindow", "9"))
        self.P2_wybor_kanalow_t.setItemText(9, _translate("MainWindow", "10"))
        self.P2_wybor_kanalow_t.setItemText(10, _translate("MainWindow", "11"))
        self.P2_wybor_kanalow_t.setItemText(11, _translate("MainWindow", "12"))
        self.P2_wybor_kanalow_t.setItemText(12, _translate("MainWindow", "13"))
        self.P2_wybor_kanalow_t.setItemText(13, _translate("MainWindow", "14"))
        self.P2_wybor_kanalow_t.setItemText(14, _translate("MainWindow", "15"))
        self.P2_wybor_kanalow_t.setItemText(15, _translate("MainWindow", "16"))
        self.P2_wybor_kanalow_t.setItemText(16, _translate("MainWindow", "17"))
        self.P2_wybor_kanalow_t.setItemText(17, _translate("MainWindow", "18"))
        self.P2_wybor_kanalow_t.setItemText(18, _translate("MainWindow", "19"))
        self.P2_wybor_kanalow_t.setItemText(19, _translate("MainWindow", "20"))

        self.P2_wybor_kanalow_tekst_p1.setText(_translate("MainWindow", "Wybór kanału:"))
        self.P2_wybor_kanalow_tekst_p2.setText(_translate("MainWindow", "Wybór kanału:"))
        self.P2_wybor_osix_tekst_p1.setText(_translate("MainWindow", "Dane osi X:"))

        self.P2_wybor_osix_p1.setItemText(0, _translate("MainWindow", "t [s]"))
        self.P2_wybor_osix_p1.setItemText(1, _translate("MainWindow", "T [K]"))
        self.P2_wybor_osix_tekst_p2.setText(_translate("MainWindow", "Dane osi X:"))
        self.P2_wybor_osix_p2.setItemText(0, _translate("MainWindow", "t [s]"))
        self.P2_wybor_osix_p2.setItemText(1, _translate("MainWindow", "T [K]"))
        self.P2_wybor_kanalow_tekst_t.setText(_translate("MainWindow", "Wybór kanału:"))

        self.P2_czestotliowsc_tekst.setText(_translate("MainWindow", "Częstotliwość próbkowania [s]:"))

        self.P2_temperatura_tekst.setText(_translate("MainWindow", "Aktualna temperatura [K]:"))
        self.P2_temperatura.setText(_translate("MainWindow", "0"))
        
        self.P2_tempo_tekst.setText(_translate("MainWindow", "Tempo przyrostu temperatury [K/min.]:"))
        self.P2_tempo.setText(_translate("MainWindow", "0"))
        self.P2_sledzenie_temp_tekst.setText(_translate("MainWindow", "Automatyczne śledzenie temperatury [K]:"))
        
        self.P2_moc_tekst.setText(_translate("MainWindow", "Moc grzałki [%]:"))
        self.P2_moc.setText(_translate("MainWindow", "0"))
        
        self.P2_start.setText(_translate("MainWindow", "Start"))
        self.P2_reset.setText(_translate("MainWindow", "Reset"))
        self.P2_licznik.setText(_translate("MainWindow", "00:00"))

        self.P2_zakres_tekst_p1.setText(_translate("MainWindow", "Zakres:"))
        self.P2_zakres_p1.setCurrentText(_translate("MainWindow", "1 M"))
        self.P2_zakres_p1.setItemText(0, _translate("MainWindow","100 R"))
        self.P2_zakres_p1.setItemText(1, _translate("MainWindow","1 k"))
        self.P2_zakres_p1.setItemText(2, _translate("MainWindow", "10 k"))
        self.P2_zakres_p1.setItemText(3, _translate("MainWindow", "100 k"))
        self.P2_zakres_p1.setItemText(4, _translate("MainWindow", "1 M"))
        self.P2_zakres_p1.setItemText(5, _translate("MainWindow", "10 M"))
        self.P2_zakres_p1.setItemText(6, _translate("MainWindow", "100 M"))
        self.P2_zakres_tekst_p2.setText(_translate("MainWindow", "Zakres:"))
        self.P2_zakres_p2.setCurrentText(_translate("MainWindow", "100 M"))
        self.P2_zakres_p2.setItemText(0, _translate("MainWindow", "100 R"))
        self.P2_zakres_p2.setItemText(1, _translate("MainWindow", "1 k"))
        self.P2_zakres_p2.setItemText(2, _translate("MainWindow", "10 k"))
        self.P2_zakres_p2.setItemText(3, _translate("MainWindow", "100 k"))
        self.P2_zakres_p2.setItemText(4, _translate("MainWindow", "1 M"))
        self.P2_zakres_p2.setItemText(5, _translate("MainWindow", "10 M"))
        self.P2_zakres_p2.setItemText(6, _translate("MainWindow", "100 M"))
    #--------->

    #<------pomiar 4-punktowy------
        self.R4_temperatura.setText(_translate("MainWindow", "0"))
        self.R4_wybor_osix_p.setItemText(0, _translate("MainWindow", "t [s]"))
        self.R4_wybor_osix_p.setItemText(1, _translate("MainWindow", "T [K]"))

        self.R4_tempo.setText(_translate("MainWindow", "0"))
        self.R4_wybor_kanalow_t.setCurrentText(_translate("MainWindow", "4"))
        self.R4_wybor_kanalow_t.setItemText(0, _translate("MainWindow", "1"))
        self.R4_wybor_kanalow_t.setItemText(1, _translate("MainWindow", "2"))
        self.R4_wybor_kanalow_t.setItemText(2, _translate("MainWindow", "3"))
        self.R4_wybor_kanalow_t.setItemText(3, _translate("MainWindow", "4"))
        self.R4_wybor_kanalow_t.setItemText(4, _translate("MainWindow", "5"))
        self.R4_wybor_kanalow_t.setItemText(5, _translate("MainWindow", "6"))
        self.R4_wybor_kanalow_t.setItemText(6, _translate("MainWindow", "7"))
        self.R4_wybor_kanalow_t.setItemText(7, _translate("MainWindow", "8"))
        self.R4_wybor_kanalow_t.setItemText(8, _translate("MainWindow", "9"))
        self.R4_wybor_kanalow_t.setItemText(9, _translate("MainWindow", "10"))
        self.R4_wybor_kanalow_t.setItemText(10, _translate("MainWindow", "11"))
        self.R4_wybor_kanalow_t.setItemText(11, _translate("MainWindow", "12"))
        self.R4_wybor_kanalow_t.setItemText(12, _translate("MainWindow", "13"))
        self.R4_wybor_kanalow_t.setItemText(13, _translate("MainWindow", "14"))
        self.R4_wybor_kanalow_t.setItemText(14, _translate("MainWindow", "15"))
        self.R4_wybor_kanalow_t.setItemText(15, _translate("MainWindow", "16"))
        self.R4_wybor_kanalow_t.setItemText(16, _translate("MainWindow", "17"))
        self.R4_wybor_kanalow_t.setItemText(17, _translate("MainWindow", "18"))
        self.R4_wybor_kanalow_t.setItemText(18, _translate("MainWindow", "19"))
        self.R4_wybor_kanalow_t.setItemText(19, _translate("MainWindow", "20"))

        self.R4_wybor_kanalow_tekst_p.setText(_translate("MainWindow", "Wybór kanału"))
        self.R4_zakres_p.setCurrentText(_translate("MainWindow", "100 R"))
        self.R4_zakres_p.setItemText(0, _translate("MainWindow","100 R"))
        self.R4_zakres_p.setItemText(1, _translate("MainWindow","1 k"))
        self.R4_zakres_p.setItemText(2, _translate("MainWindow", "10 k"))
        self.R4_zakres_p.setItemText(3, _translate("MainWindow", "100 k"))
        self.R4_zakres_p.setItemText(4, _translate("MainWindow", "1 M"))
        self.R4_zakres_p.setItemText(5, _translate("MainWindow", "10 M"))
        self.R4_zakres_p.setItemText(6, _translate("MainWindow", "100 M")) 

        self.R4_skala_log_p.setText(_translate("MainWindow", "Skala log"))
        self.R4_tempo_tekst.setText(_translate("MainWindow", "Tempo przyrostu temperatury [K/min.]:"))
        self.R4_czestotliowsc_tekst.setText(_translate("MainWindow", "Częstotliwość próbkowania [s]"))
        self.R4_sledzenie_temp_tekst.setText(_translate("MainWindow", "Automatyczne śledzenie temperatury [K]"))
        self.R4_zakres_tekst.setText(_translate("MainWindow", "Zakres:"))
        self.R4_moc_tekst.setText(_translate("MainWindow", "Moc grzałki [%]:"))
        self.R4_wybor_kanalow_tekst_t.setText(_translate("MainWindow", "Wybór kanału"))
        self.R4_wybor_kanalow_p.setCurrentText(_translate("MainWindow", "4"))
        self.R4_wybor_kanalow_p.setItemText(0, _translate("MainWindow", "1"))
        self.R4_wybor_kanalow_p.setItemText(1, _translate("MainWindow", "2"))
        self.R4_wybor_kanalow_p.setItemText(2, _translate("MainWindow", "3"))
        self.R4_wybor_kanalow_p.setItemText(3, _translate("MainWindow", "4"))
        self.R4_wybor_kanalow_p.setItemText(4, _translate("MainWindow", "5"))
        self.R4_wybor_kanalow_p.setItemText(5, _translate("MainWindow", "6"))
        self.R4_wybor_kanalow_p.setItemText(6, _translate("MainWindow", "7"))
        self.R4_wybor_kanalow_p.setItemText(7, _translate("MainWindow", "8"))
        self.R4_wybor_kanalow_p.setItemText(8, _translate("MainWindow", "9"))
        self.R4_wybor_kanalow_p.setItemText(9, _translate("MainWindow", "10"))

        self.R4_moc.setText(_translate("MainWindow", "0"))
        self.R4_wybor_osix_tekst_p.setText(_translate("MainWindow", "Dane osi X:"))
        self.R4_skala_log_t.setText(_translate("MainWindow", "Skala log"))
        self.R4_temperatura_tekst.setText(_translate("MainWindow", "Aktualna temperatura [K]:"))
        self.R4_start.setText(_translate("MainWindow", "Start"))
        self.R4_reset.setText(_translate("MainWindow", "Reset"))
        self.R4_licznik.setText(_translate("MainWindow", "00:00"))
    #--------------->


    #<----tryb reczny---    
        self.label_1.setText(_translate("MainWindow", "Kanał 1"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_11.setText(_translate("MainWindow", "Kanał 11"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_2.setText(_translate("MainWindow", "Kanał 2"))
        self.label_12.setText(_translate("MainWindow", "Kanał 12"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_3.setText(_translate("MainWindow", "Kanał 3"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_13.setText(_translate("MainWindow", "Kanał 13"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_4.setText(_translate("MainWindow", "Kanał 4"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_14.setText(_translate("MainWindow", "Kanał 14"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_5.setText(_translate("MainWindow", "Kanał 5"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_15.setText(_translate("MainWindow", "Kanał 15"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_6.setText(_translate("MainWindow", "Kanał 6"))
        self.label_16.setText(_translate("MainWindow", "Kanał 16"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_7.setText(_translate("MainWindow", "Kanał 7"))
        self.label_17.setText(_translate("MainWindow", "Kanał 17"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_8.setText(_translate("MainWindow", "Kanał 8"))
        self.label_18.setText(_translate("MainWindow", "Kanał 18"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_9.setText(_translate("MainWindow", "Kanał 9"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_19.setText(_translate("MainWindow", "Kanał 19"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.label_10.setText(_translate("MainWindow", "Kanał 10"))
        self.label_20.setText(_translate("MainWindow", "Kanał 20"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Napięcie [v]"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "Opór [Ohm]"))
        self.CH20_skala_log.setText(_translate("MainWindow", "Skala log"))
        self.CH20_czestotliowsc_in_tekst.setText(_translate("MainWindow", "Okres między kanałami [s]"))
        self.CH20_czestotliowsc_out_tekst.setText(_translate("MainWindow", "Okres między seriami [s]"))
        self.CH20_start.setText(_translate("MainWindow", "Start"))
        self.CH20_reset.setText(_translate("MainWindow", "Reset"))
        self.CH20_licznik.setText(_translate("MainWindow", "00:00"))
    #----------------->
    
    #<--------------inne-----------
        self.zmiana_trybu.setItemText(0, _translate("MainWindow", "Pomiar oporu w funkcji temeperatury"))
        self.zmiana_trybu.setItemText(1, _translate("MainWindow", "Pomiar 4-punktowy"))
        self.zmiana_trybu.setItemText(2, _translate("MainWindow", "Ręczny"))
        self.zmiana_trybu_tekst.setText(_translate("MainWindow", "Tryb: "))
        self.naglowek.setText(_translate("MainWindow", "Nazwa_pomiaru"))
        self.nazwa_pliku_tekst.setText(_translate("MainWindow", "Nazwa pliku wyjściowego:"))
        self.nazwa_pliku_przedrostek.setText(_translate("MainWindow", "data_"))
        self.Ustawienia.setText(_translate("MainWindow", "Ustawienia"))
        self.Pomoc.setText(_translate("MainWindow", "Pomoc"))
    #--------->

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())